<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEERBnCL\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEERBnCL/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEERBnCL.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEERBnCL\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerEERBnCL\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'EERBnCL',
    'container.build_id' => 'bede5afd',
    'container.build_time' => 1657554284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEERBnCL');
